# Generated by Django 4.2.5 on 2023-09-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_categories', '0002_alter_bookcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
