# Generated by Django 4.2.5 on 2023-09-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_categories', '0003_alter_bookcategory_name'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_categories.bookcategory', to_field='name'),
        ),
    ]
