# Generated by Django 4.2.5 on 2023-10-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_categories', '0003_alter_bookcategory_name'),
        ('books', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_categories.bookcategory'),
        ),
    ]
